name: server

on:
  push:
    branches: ["server"]
  pull_request:
    branches: ["server"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: 上传项目到华为云
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          source: ./*
          target: /root/web-server
          tar_dereference: true
          script_after: \
            "npm install"
