name: server

on:
  push:
    branches: ["server"]
  pull_request:
    branches: ["server"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装依赖
        run: npm install

      - name: 上传项目到华为云
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          source: ./*
          target: /root/web-server
          tar_dereference: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          # push: true
          tags: my-app
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 启动容器
        uses: docker/build-push-action@v2
        with:
          action: run
          image: my-app
          options: -d -p 1216:1216 --name web-server
